### ISSUE TITLE
build

### ISSUE THREAD

**Issue by srinigudimella** [AntonovSergey2211/guepard#2]
How to build converter.air?

**Comment by superman2211** [comment]
Hi! 

I added **Build** section into [readme file](https://github.com/AntonovSergey2211/guepard/blob/master/README.md)

**Comment by srinigudimella** [comment]
Hi,
Thank you for your support. I followed step by step. Created new project
name as New project and added all the source files Built successfully
executed. But when we run, then below error is showing.
"Running process: C:\Program Files (x86)\FlashDevelop\Tools\fdbuild\fdbuild.exe "D:\Srini\Flex\New Project\New Project.as3proj" -ipc b7011240-395b-43be-89e1-b9a7ce99d2fc -version "4.6.0; 3.1" -compiler "C:\Users\Srini\Downloads\flex_sdk_4.6" -library "C:\Program Files (x86)\FlashDevelop\Library"
Building New Project
Build succeeded
Done(0)
The system cannot find the file specified
[No debug Flash player connection request]
"
One clarification that converter.swf in applicaiton.xml path is not in the
source. Is this causing error?

Please advise. Thank you.

**Comment by superman2211** [comment]
Hi!

I updated **Build** instruction.

If you want to use this converter for convert **flash** app to **html5** you can install only **Adobe AIR** and compiled **air/converter.air**.

**Comment by srinigudimella** [comment]
Thank you for your support. I followed all the instructions and run the build . The error screenshot is attached. I am not having knowledge in Air application. Can you please support on this.

![runerror](https://user-images.githubusercontent.com/19509457/52250555-6a425300-291e-11e9-9819-623a2bffb184.PNG)

**Comment by superman2211** [comment]
Hi!
Your **APP_ID** does not match with id from **application.xml**.

**application.xml**
`<id>converter</id> `

**SetupApp.bat**
`set CERT_NAME="converter"`

Also, you need to rebuild your certificate.

**Comment by srinigudimella** [comment]
Hi,

The below is the file application.xml

<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
  <id>converter</id>
  <versionNumber>1.0</versionNumber>
  <filename>converter</filename>
  <name>converter</name>
  <initialWindow>
    <title>converter</title>
    <content>converter.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <minimizable>true</minimizable>
    <maximizable>true</maximizable>
    <resizable>true</resizable>
  </initialWindow>
  
  <supportedProfiles>desktop</supportedProfiles>
  <android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto"
xmlns:android="http://schemas.android.com/apk/res/android"
/>]]></manifestAdditions>
  </android>
</application>
The "setupApp.bat" file contents are

:: Set working dir
cd %~dp0 & cd ..

:user_configuration

:: About AIR application packaging
::
http://livedocs.adobe.com/flex/3/html/help.html?content=CommandLineTools_5.html#1035959
:: http://livedocs.adobe.com/flex/3/html/distributing_apps_4.html#1037515

:: NOTICE: all paths are relative to project root

:: Your certificate information
set CERT_NAME=converter
set CERT_PASS=39#wnetx3tl
set CERT_FILE=bat\converter.p12
set SIGNING_OPTIONS=-storetype pkcs12 -keystore %CERT_FILE% -storepass
%CERT_PASS% -tsa none


:: Application descriptor
set APP_XML=application.xml

:: Files to package
set APP_DIR=bin
set FILE_OR_DIR=-C %APP_DIR% .

:: Your application ID (must match <id> of Application descriptor) and
remove spaces
for /f "tokens=3 delims=<>" %%a in ('findstr /R /C:"^[ ]*<id>" %APP_XML%')
do set APP_ID=%%a
set APP_ID=%APP_ID: =%

:: Output
set AIR_PATH=air
set AIR_NAME="converter"

:validation
findstr /D:"<id>%APP_ID%</id>" "%APP_XML%" > NUL
if errorlevel 1 goto badid
goto end

:badid
echo.
echo ERROR:
echo   Application ID in 'bat\SetupApp.bat' (APP_ID)
echo   does NOT match Application descriptor '%APP_XML%' (id)
echo.
if %PAUSE_ERRORS%==1 pause
exit

:end

Not able to create certificate it says arguments are not enough.
Can you please let me know what is the issue?

Thank you.

**Comment by superman2211** [comment]
Hi! 
Your files didn't work for me. Build completed but I don't see anything...
Try those files:

**application.xml**
<?xml version="1.0" encoding="utf-8"?> 
<application xmlns="http://ns.adobe.com/air/application/26.0">
	
	<id>converter</id> 
	<versionNumber>1.0</versionNumber> 
	<filename>converter</filename> 
	
	<name>converter</name> 
	<description></description> 
	<copyright></copyright> 
	
	<initialWindow> 
		<title>converter</title> 
		<content>converter.swf</content> 
		<systemChrome>standard</systemChrome> 
		<transparent>false</transparent> 
		<visible>true</visible> 
		<minimizable>true</minimizable> 
		<maximizable>true</maximizable> 
		<resizable>true</resizable> 
	</initialWindow> 
	
	
</application>

**SetupApp.bat**

> :: Set working dir
> cd %~dp0 & cd ..
> 
> :user_configuration
> 
> :: About AIR application packaging
> :: http://livedocs.adobe.com/flex/3/html/help.html?content=CommandLineTools_5.html#1035959
> :: http://livedocs.adobe.com/flex/3/html/distributing_apps_4.html#1037515
> 
> :: NOTICE: all paths are relative to project root
> 
> :: Your certificate information
> set CERT_NAME="converter"
> set CERT_PASS=fd
> set CERT_FILE="bat\converter.p12"
> set SIGNING_OPTIONS=-storetype pkcs12 -keystore %CERT_FILE% -storepass %CERT_PASS%
> 
> :: Application descriptor
> set APP_XML=application.xml
> 
> :: Files to package
> set APP_DIR=bin
> set FILE_OR_DIR=-C %APP_DIR% .
> 
> :: Your application ID (must match <id> of Application descriptor) and remove spaces
> for /f "tokens=3 delims=<>" %%a in ('findstr /R /C:"^[ 	]*<id>" %APP_XML%') do set APP_ID=%%a
> set APP_ID=%APP_ID: =%
> 
> :: Output
> set AIR_PATH=air
> set AIR_NAME=converter
> 
> :validation
> findstr /C:"<id>%APP_ID%</id>" "%APP_XML%" > NUL
> if errorlevel 1 goto badid
> goto end
> 
> :badid
> echo.
> echo ERROR: 
> echo   Application ID in 'bat\SetupApp.bat' (APP_ID) 
> echo   does NOT match Application descriptor '%APP_XML%' (id)
> echo.
> if %PAUSE_ERRORS%==1 pause
> exit
> 
> :end

**Comment by srinigudimella** [comment]
At the first step, the certificate is not working.. See attached error.
![capture1](https://user-images.githubusercontent.com/19509457/52437296-989d7980-2b3c-11e9-8540-18c6c00b927d.PNG)

**Comment by superman2211** [comment]
Hello! Do you have any updates?
