### ISSUE TITLE
Not understanding the process

### ISSUE THREAD

**Issue by BracerJack** [AntonovSergey2211/guepard#3]
Hi, I have been on the lookout for all *.swf to HTML 5 tools and I have had very promising success with SWF2JS and Mozilla :: Shumway.

SWF2JS works very well for ActionScript 2 and while Mozilla Shumway works really well for ActionScript 3 and even handles some very advance bitmap manipulation codes very well !

I have had some trouble trying to use your tool to run through my test to see how well this works.

I am not really understanding the procedure, attached is the *.swf test.

1: Created a project, your program direct me to the settings tab asking me for the SDK path ?
Which SDK are we talking about ? The Flex SDK ? or the sdk from guepard-master ?
If it is from guepard-master, to select the folder where the sdk folder is or go INTO the sdk file itself ?

2: Under source, it ask for so many stuff, it is rather confusing so I just pick one file "FlashSavingTestKit.swf" which I have attached here for you.
I also have the fla files and stuff but when I include them the program hangs, the point is I am confused as to what exactly does this program need.

3: When I click convert it got stuck on "Generate Atlases Complete".

**Comment by superman2211** [comment]
Hi! Sorry could not answer quickly.

1.  **SDK Path** it is path to **sdk** folder from **guepard-master**
2. Main idea of this converter - convert source **as3** code into **js** with help **swf** and **fla**. You need to set it all for best result. Converter parse code and looking for **as3** code in sources and in the **fla**. 
3. If program is freezed - It may be bug ) Please, try easy tests for begin.
4. My skype - **superflasher22** Welcome! )

**Comment by BracerJack** [comment]
I have made a very simple Flash converter test program that test for four basic capabilities of all flash to html 5 tools.
Please try to see if you could make your tool pass this 4 basic test
https://mega.nz/#!CvwU3IIT!4Wi3K-iS3qkbYgkE77xzJRp2PHy8JWlz82ErwgtRZiQ

It is created using Flash CS3 [the bare minimum of ActionScript 3 support, if this fail...I don't see how this can continue.]

I couldn't get your system to exit the preloader you have created.
Thank you for your help.

I will add you to skype when I install skype again very soon.
