### ISSUE TITLE
Any chance to succeed without the AS3 code ?

### ISSUE THREAD

**Issue by fusiller** [AntonovSergey2211/guepard#4]
Hi,
congrats for this great work.
My kids have their teachers send them to  a lot of flash player based animations created by other school teachers years ago, that nobody can use any more.
I tried to help in downloading the SWF and converting it thanks to your app. I produce interesting results but not quite what it should look like.
Exemple here : http://www.pccl.fr/physique_chimie_college_lycee/quatrieme/electricite/lois_intensites_noeuds_mesures.htm

**Comment by superman2211** [comment]
Hey! Thanks. 
Unfortunately, this is not possible without the as3 code. I also tried decompiling your SWF, and as2 code was found there. It is not compatible with this tool.

**Comment by superman2211** [comment]
You can enable flash player for your site in the Google Chrome. Follow [this instruction](https://support.google.com/chrome/answer/6258784?co=GENIE.Platform%3DDesktop&hl=en).

You can try [this SWF player](https://github.com/ienaga/swf2js) written on js. 
This player able to work with as2.

Also you can download [Adobe Flash Player](https://www.adobe.com/support/flashplayer/debug_downloads.html) for desktop and use it.

**Comment by fusiller** [comment]
Thank you very much for your help.
