### ISSUE TITLE
SWF/MovieClip frame labels not transferred

### ISSUE THREAD

**Issue by isi-dwade** [AntonovSergey2211/guepard#7]
When XML of SWF is loaded, FrameLabels are loaded but when MovieClip used, FrameLabels array is blank.

**Comment by superman2211** [comment]
Hi! Do you have a sample?

**Comment by isi-dwade** [comment]
Hello Sergey,
I don’t have a self-contained sample, but would you be willing to share your email address or phone/skype/zoom directly with me to discuss options?
Possible options could be you giving advice, consulting, or ongoing working relationship.

Thank you

Derek Wade
Chief Software Engineer/Architect
Individual Software Inc.
3049 Independence Drive, Suite E
Livermore, CA  94551
dwade@individualsoftware.com<mailto:dwade@individualsoftware.com>

**Comment by isi-dwade** [comment]
Or if you'd prefer just a sample, I can put one together.
Thanks.

**Comment by superman2211** [comment]
Hi! My skype **superflasher22**

**Comment by isi-dwade** [comment]
Needed to extract actionscript from assets as actionScript Class names.
